### ISSUE TITLE
Bad error message if k chosen poorly

### ISSUE THREAD

**Issue by pbreheny** [areisett/penalizedLMM#3]
```r
library(penalizedLMM)
X <- matrix(rnorm(100, 10), 100, 10)
y <- rnorm(100)
plmm(X, y, k=12)
#> Error in plmm_prep(X = X, ...): object 'decomp' not found
```

**Comment by tabpeter** [comment]
The error message is now informative: 
`X <- matrix(rnorm(100, 10), 100, 10)
y <- rnorm(100)
plmm(X, y, k=12)
Error in plmm_prep(X = X, y = y, K = K, k = k, diag_K = diag_K, eta_star = eta_star,  : 
  k value is out of bounds. 
If specified, k must be in the range from 1 to min(nrow(X), ncol(X))`
