### ISSUE TITLE
response -> lp?

### ISSUE THREAD

**Issue by pbreheny** [areisett/penalizedLMM#6]
In my opinion, `"response"` is a poor name for the `type=` option in `cv.plmm()`. I believe it should be called `lp` or `linear` for linear predictor. Both the BLUP and the LP are predicting the response; the question is whether they include a covariance adjustment or not.

**Comment by tabpeter** [comment]
'response' is now changed to 'lp' (I didn't realize 'fixing' was not a keyword...)
