### ISSUE TITLE
Dependencies when installing 

### ISSUE THREAD

**Issue by yujideng** [areisett/penalizedLMM#7]
When installing the package, this error shows up: ERROR: dependency 'SNPRelate' is not available for package 'penalizedLMM'. Should probably make SNPRelate (and BiocManager) automatically installed?

**Comment by pbreheny** [comment]
SNPrelate shouldn't be a dependency at all.

**Comment by tabpeter** [comment]
Dependency is removed -- from here on out, packages bigstatsr and bigsnpr will replace snpStats and SNPRelate

**Comment by pbreheny** [comment]
Perhaps bigsnpr should be under `Suggests:`? If I intend to use `plmm` on non-genetic data, why should I have to install `bigsnpr`?

**Comment by pbreheny** [comment]
While we're at it, do we need a dependency on `popkin`?
